const TEST = "TEST";
const SEARCH_NAME_START = "SEARCH_NAME_START";
const SEARCH_NAME_SUCCEED = "SEARCH_NAME_SUCCEED";
const SEARCH_NAME_FAIL = "SEARCH_NAME_FAIL";

const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export default {
  TEST,
  SEARCH_NAME_START,
  SEARCH_NAME_SUCCEED,
  SEARCH_NAME_FAIL,
  SET_ERROR_MESSAGE,
};
