const TEST = "TEST";
const FETCH_ALLDATA_START = "FETCH_ALLDATA_START";
const FETCH_ALLDATA_SUCCEED = "FETCH_ALLDATA_SUCCEED";
const FETCH_ALLDATA_FAIL = "FETCH_ALLDATA_FAIL";

const SEARCH_NAME_START = "SEARCH_NAME_START";
const SEARCH_NAME_SUCCEED = "SEARCH_NAME_SUCCEED";
const SEARCH_NAME_FAIL = "SEARCH_NAME_FAIL";

const SEARCH_DETAILS_START = "SEARCH_DETAILS_START";
const SEARCH_DETAILS_SUCCEED = "SEARCH_DETAILS_SUCCEED";
const SEARCH_DETAILS_FAIL = "SEARCH_DETAILS_FAIL";

const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

const SET_SELECT_DATA = "SET_SELECT_DATA";

export default {
  TEST,
  FETCH_ALLDATA_START,
  FETCH_ALLDATA_SUCCEED,
  FETCH_ALLDATA_FAIL,
  SEARCH_NAME_START,
  SEARCH_NAME_SUCCEED,
  SEARCH_NAME_FAIL,
  SEARCH_DETAILS_START,
  SEARCH_DETAILS_SUCCEED,
  SEARCH_DETAILS_FAIL,
  SET_ERROR_MESSAGE,
  SET_SELECT_DATA,
};
